### ISSUE TITLE
Should we update airports with nearby MSFS matches?

### ISSUE THREAD

**Issue by vladyi74** [Bahnzo/canIflythere.json#4]
What I mean with that:  I've found some ICAO which correctly register in FSE but they do not have the same lat/long as target FSE airport (not an exact match).

Here are some examples:
`FSE     MSFS`
`==== =====`
`LSGC LFIA 10Km away`
`LFXI LF64 11Km away`
`EGNA EGXO 10Km away`

I think updating these ICAOs will help too.
What do you think?

**Comment by Bahnzo** [comment]
No. I get the idea, but the best way would be to put actual airports there. And in some cases, there are actual airports there, but for various reasons MSFS doesn't have them. Aliasing them only to have people build airports or MSFS update and add them would just cause further problems.

**Comment by vladyi74** [comment]
OK, got it; we'll put only exact matches.
